version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Getting Started

  build:
    commands:
      - npx express-generator
      - npm install

artifacts:
  files:
    - "**/*"
